[package]
name = "platformer"
version = "0.0.1"
authors = ["Nick Spain <nicholas.spain96@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.13.2"

[features]
# Works for linux and window, but not for macOS. Instead you must use:
#    cargo build --no-default-features --features metal
default = ["vulkan"]

empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
