version: 2.1

jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install system deps
          command: |
            sudo apt install libasound2-dev libx11-xcb-dev libssl-dev
      - run:
          name: Versions
          command: |
            rustc --version
            cargo --version
            rustup --version
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Install cargo components
          command: |
            rustup component add clippy
            rustup component add rustfmt
      - run:
          name: Linters
          command: |
            cargo fmt -- --check
            cargo check --features empty
            cargo clippy --features empty -- -D warnings
      - run:
          name: Test
          command: |
            cargo test --features empty
      - save_cache:
          paths:
            - "~/.cargo"
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
