name: Build and test

on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt-get install -y libasound2-dev

      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install clippy
        uses: actions-rs/components-nightly@v1
        with:
          target: x86_64-unknown-linux-gnu
          component: clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          arguments: --features vulkan
      - name: Run rustfmt in check mode
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          arguments: --features vulkan --  --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          arguments: --features vulkan -- -D warnings

  build_test_linux:
    name: Linux build/test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt-get install -y libasound2-dev
      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          arguments: --features vulkan

  build_test_windows:
    name: Windows build/test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          arguments: --features vulkan

  # macOS needs to be build separately because we need the 'metal' feature, not 'vulkan'
  build_test_macos:
    name: Build and test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          arguments: --features metal
