name: Build and test

on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/components-nightly@v1
        with:
          target: x86_64-unknown-linux-gnu
          component: clippy

      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: rustfmt
          argumentss: --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          argumentss: -- -D warnings

  build_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    name: Build and test on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          arguments: --no-default-features --features vulkan

  # macOS needs to be build separately because we need the 'metal' feature, not 'vulkan'
  build_test_macos:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          arguments: --no-default-features --features metal
