name: CI

on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt-get install -y libasound2-dev

      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install clippy
        uses: actions-rs/components-nightly@v1
        with:
          target: x86_64-unknown-linux-gnu
          component: clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features vulkan
      - name: Run rustfmt in check mode
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --  --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features vulkan -- -D warnings

  build_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    name: ${{ matrix.platform }} build/test
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get install -y gcc pkg-config openssl libasound2-dev build-essential \
              python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
        if: matrix.platform ==  'ubuntu-latest'
      - name: Setup rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features empty
